#!/bin/bash
images=(kube-apiserver:v1.12.2
        kube-controller-manager:v1.12.2
        kube-scheduler:v1.12.2
        kube-proxy:v1.12.2
        pause:3.1
        etcd:3.2.24
        coredns:1.2.2)
for image in ${images[@]} ; do
  docker pull runzee/$image
  docker tag runzee/$image  k8s.gcr.io/$image
  docker rmi runzee/$image
done
